---

- name: remove bootstrapped file from host
  file:
    state: absent
    path: '/root/.bootstrap_complete'

- name: Wipe disklabel
  command: sgdisk -Z {{ item }}
  with_items: "{{ _target_devices }}"

- name: discard device
  command: blkdiscard {{ item }}
  failed_when: False
  with_items: "{{ _target_devices }}"
